version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:3000"  # Frontend
      - "3001:3001"  # Backend API
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    
  # PostgreSQL database (uncomment when backend is ready)
  # db:
  #   image: postgres:15-alpine
  #   environment:
  #     POSTGRES_DB: mcculloch_jewelry
  #     POSTGRES_USER: ${DB_USER:-postgres}
  #     POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   restart: unless-stopped

# volumes:
#   postgres_data: