UPDATE products SET ring_styles = ARRAY['Solitaire','Modern/Contemporary','Bridal Set','Shoulder Set'] WHERE sku = 'BJ-001';
UPDATE products SET ring_styles = ARRAY['5 Stones','Bridal Set'] WHERE sku = 'BJ-002';
UPDATE products SET ring_styles = ARRAY['Solitaire','Shoulder Set'] WHERE sku = 'BJ-003';
UPDATE products SET ring_styles = ARRAY['Solitaire','Cross Over'] WHERE sku = 'BJ-004';
UPDATE products SET ring_styles = ARRAY['Solitaire','Shoulder Set','Cross Over'] WHERE sku = 'BJ-005';
UPDATE products SET ring_styles = ARRAY['Solitaire','Shoulder Set','Cross Over'] WHERE sku = 'BJ-006';
UPDATE products SET ring_styles = ARRAY['Halo','Vintage','Shoulder Set'] WHERE sku = 'BJ-007';
UPDATE products SET ring_styles = ARRAY['Shoulder Set','Wed-fit'] WHERE sku = 'BJ-008';
UPDATE products SET ring_styles = ARRAY['Halo','Shoulder Set'] WHERE sku = 'BJ-009';
UPDATE products SET ring_styles = ARRAY[]::TEXT[] WHERE sku = 'BJ-010';
UPDATE products SET ring_styles = ARRAY['Solitaire','Hidden Halo'] WHERE sku = 'BJ-011';
UPDATE products SET ring_styles = ARRAY['Solitaire','Shoulder Set','Modern/Contemporary','Cross Over'] WHERE sku = 'BJ-012';
UPDATE products SET ring_styles = ARRAY['Vintage','Solitaire','Shoulder Set'] WHERE sku = 'BJ-013';
UPDATE products SET ring_styles = ARRAY['Shoulder Set','Vintage','Bridal Set','Bezel'] WHERE sku = 'BJ-014';
UPDATE products SET ring_styles = ARRAY['Shoulder Set','Vintage','Wed-fit'] WHERE sku = 'BJ-015';
UPDATE products SET ring_styles = ARRAY['Halo','Shoulder Set','Vintage'] WHERE sku = 'BJ-016';
UPDATE products SET ring_styles = ARRAY['Modern/Contemporary','Solitaire','Cross Over','Shoulder Set','Bridal Set'] WHERE sku = 'BJ-017';
UPDATE products SET ring_styles = ARRAY['Modern/Contemporary','Solitaire','Shoulder Set','Bridal Set'] WHERE sku = 'BJ-018';
UPDATE products SET ring_styles = ARRAY['Shoulder Set','Vintage','Bridal Set'] WHERE sku = 'BJ-019';
UPDATE products SET ring_styles = ARRAY['Halo','Vintage','Shoulder Set','Bridal Set'] WHERE sku = 'BJ-020';
UPDATE products SET ring_styles = ARRAY['Solitaire','Wed-fit'] WHERE sku = 'BJ-021';
UPDATE products SET ring_styles = ARRAY['Solitaire','Wed-fit','Bridal Set'] WHERE sku = 'BJ-023';
UPDATE products SET ring_styles = ARRAY['Solitaire','Cross Over','Modern/Contemporary','Bridal Set'] WHERE sku = 'BJ-024';
UPDATE products SET ring_styles = ARRAY['Solitaire'] WHERE sku = 'BJ-025';
UPDATE products SET ring_styles = ARRAY['Shoulder Set','Cross Over'] WHERE sku = 'BJ-026';
UPDATE products SET ring_styles = ARRAY['Solitaire','Cross Over'] WHERE sku = 'BJ-027';
UPDATE products SET ring_styles = ARRAY['Solitaire','Wed-fit'] WHERE sku = 'BJ-028';
UPDATE products SET ring_styles = ARRAY['Shoulder Set','Solitaire'] WHERE sku = 'BJ-029';
UPDATE products SET ring_styles = ARRAY['Solitaire','Wed-fit'] WHERE sku = 'BJ-030';
UPDATE products SET ring_styles = ARRAY['Solitaire','Shoulder Set'] WHERE sku = 'BJ-031';
UPDATE products SET ring_styles = ARRAY['Solitaire','Hidden Halo'] WHERE sku = 'BJ-032';
UPDATE products SET ring_styles = ARRAY['Trilogy','Shoulder Set','Bridal Set'] WHERE sku = 'BJ-033';
UPDATE products SET ring_styles = ARRAY['Trilogy'] WHERE sku = 'BJ-034';
UPDATE products SET ring_styles = ARRAY['Trilogy','Modern/Contemporary','Cross Over','Shoulder Set'] WHERE sku = 'BJ-035';
UPDATE products SET ring_styles = ARRAY['Trilogy'] WHERE sku = 'BJ-036';
UPDATE products SET ring_styles = ARRAY['Trilogy'] WHERE sku = 'BJ-037';
UPDATE products SET ring_styles = ARRAY['Trilogy','Shoulder Set'] WHERE sku = 'BJ-038';
UPDATE products SET ring_styles = ARRAY['Trilogy'] WHERE sku = 'BJ-039';
UPDATE products SET ring_styles = ARRAY['Trilogy'] WHERE sku = 'BJ-040';
UPDATE products SET ring_styles = ARRAY['Trilogy'] WHERE sku = 'BJ-041';
UPDATE products SET ring_styles = ARRAY['Trilogy'] WHERE sku = 'BJ-042';
UPDATE products SET ring_styles = ARRAY['Trilogy'] WHERE sku = 'BJ-043';
UPDATE products SET ring_styles = ARRAY['Trilogy','Shoulder Set','Vintage'] WHERE sku = 'BJ-044';
UPDATE products SET ring_styles = ARRAY['Trilogy'] WHERE sku = 'BJ-045';
UPDATE products SET ring_styles = ARRAY['Solitaire','Hidden Halo','Wed-fit','Bridal Set'] WHERE sku = 'BJ-046';
UPDATE products SET ring_styles = ARRAY['Halo'] WHERE sku = 'BJ-047';
UPDATE products SET ring_styles = ARRAY['Solitaire','Hidden Halo','Wed-fit','Bridal Set'] WHERE sku = 'BJ-048';
UPDATE products SET ring_styles = ARRAY['Halo','Wed-fit','Bridal Set'] WHERE sku = 'BJ-049';
UPDATE products SET ring_styles = ARRAY['Halo','Shoulder Set','Wed-fit','Bridal Set'] WHERE sku = 'BJ-050';
UPDATE products SET ring_styles = ARRAY['Solitaire','Cross Over','Shoulder Set'] WHERE sku = 'BJ-051';
UPDATE products SET ring_styles = ARRAY['Trilogy'] WHERE sku = 'BJ-052';
UPDATE products SET ring_styles = ARRAY['Trilogy','Shoulder Set'] WHERE sku = 'BJ-053';
UPDATE products SET ring_styles = ARRAY['Trilogy','Wed-fit','Bridal Set'] WHERE sku = 'BJ-054';
UPDATE products SET ring_styles = ARRAY['Trilogy'] WHERE sku = 'BJ-055';
UPDATE products SET ring_styles = ARRAY['Shoulder Set','Cross Over'] WHERE sku = 'BJ-056';
UPDATE products SET ring_styles = ARRAY['Halo','Shoulder Set'] WHERE sku = 'BJ-057';
UPDATE products SET ring_styles = ARRAY['Solitaire','Modern/Contemporary','Cross Over','Shoulder Set'] WHERE sku = 'BJ-058';
UPDATE products SET ring_styles = ARRAY['2 Stones','Modern/Contemporary'] WHERE sku = 'BJ-059';
UPDATE products SET ring_styles = ARRAY['Modern/Contemporary'] WHERE sku = 'BJ-060';
UPDATE products SET ring_styles = ARRAY['Vintage','2 Stones','Halo'] WHERE sku = 'BJ-061';
UPDATE products SET ring_styles = ARRAY['Vintage','Halo','Shoulder Set'] WHERE sku = 'BJ-062';
UPDATE products SET ring_styles = ARRAY['Vintage','Halo','Shoulder Set'] WHERE sku = 'BJ-063';
UPDATE products SET ring_styles = ARRAY['Halo','Bridal Set','Wed-fit'] WHERE sku = 'BJ-064';
UPDATE products SET ring_styles = ARRAY['Vintage','Trilogy'] WHERE sku = 'BJ-065';
UPDATE products SET ring_styles = ARRAY['Halo'] WHERE sku = 'BJ-066';
UPDATE products SET ring_styles = ARRAY['Halo','Shoulder Set','Vintage'] WHERE sku = 'BJ-067';
UPDATE products SET ring_styles = ARRAY['Vintage','Shoulder Set'] WHERE sku = 'BJ-068';
UPDATE products SET ring_styles = ARRAY['Vintage'] WHERE sku = 'BJ-069';
UPDATE products SET ring_styles = ARRAY['Solitaire','Shoulder Set','Vintage'] WHERE sku = 'BJ-070';
UPDATE products SET ring_styles = ARRAY['Halo','Vintage','Shoulder Set'] WHERE sku = 'BJ-071';
UPDATE products SET ring_styles = ARRAY[]::TEXT[] WHERE sku = 'BJ-072';
UPDATE products SET ring_styles = ARRAY[]::TEXT[] WHERE sku = 'BJ-073';
UPDATE products SET ring_styles = ARRAY[]::TEXT[] WHERE sku = 'BJ-074';
UPDATE products SET ring_styles = ARRAY[]::TEXT[] WHERE sku = 'BJ-075';
UPDATE products SET ring_styles = ARRAY['Vintage','Halo','Shoulder Set'] WHERE sku = 'BJ-073';
UPDATE products SET ring_styles = ARRAY['Vintage','Shoulder Set'] WHERE sku = 'BJ-074';
UPDATE products SET ring_styles = ARRAY['Vintage','Halo','Shoulder Set'] WHERE sku = 'BJ-075';
UPDATE products SET ring_styles = ARRAY['Vintage','Halo'] WHERE sku = 'BJ-076';
UPDATE products SET ring_styles = ARRAY['Modern/Contemporary'] WHERE sku = 'BJ-077';
UPDATE products SET ring_styles = ARRAY['Vintage','Shoulder Set'] WHERE sku = 'BJ-078';
UPDATE products SET ring_styles = ARRAY['Vintage','Halo','Shoulder Set'] WHERE sku = 'BJ-079';
UPDATE products SET ring_styles = ARRAY['Vintage','Solitaire'] WHERE sku = 'BJ-080';
UPDATE products SET ring_styles = ARRAY['Vintage','Halo','Shoulder Set'] WHERE sku = 'BJ-081';
UPDATE products SET ring_styles = ARRAY['Vintage','Shoulder Set'] WHERE sku = 'BJ-082';
UPDATE products SET ring_styles = ARRAY['Vintage','Halo'] WHERE sku = 'BJ-083';
UPDATE products SET ring_styles = ARRAY['Vintage','Halo'] WHERE sku = 'BJ-084';
UPDATE products SET ring_styles = ARRAY['Vintage'] WHERE sku = 'BJ-085';
UPDATE products SET ring_styles = ARRAY['Vintage','2 Stones'] WHERE sku = 'BJ-086';
UPDATE products SET ring_styles = ARRAY['Vintage','Shoulder Set'] WHERE sku = 'BJ-087';
UPDATE products SET ring_styles = ARRAY['Vintage','Shoulder Set'] WHERE sku = 'BJ-088';
UPDATE products SET ring_styles = ARRAY['Modern/Contemporary','Shaped Wedding Band'] WHERE sku = 'BJ-120';
UPDATE products SET ring_styles = ARRAY['Modern/Contemporary','Shaped Wedding Band'] WHERE sku = 'BJ-121';
UPDATE products SET ring_styles = ARRAY['Vintage','Shaped Wedding Band'] WHERE sku = 'BJ-122';
UPDATE products SET ring_styles = ARRAY['Modern/Contemporary','Shaped Wedding Band'] WHERE sku = 'BJ-123';
UPDATE products SET ring_styles = ARRAY['Modern/Contemporary','Shaped Wedding Band'] WHERE sku = 'BJ-124';
UPDATE products SET ring_styles = ARRAY['Modern/Contemporary','Shaped Wedding Band'] WHERE sku = 'BJ-125';
UPDATE products SET ring_styles = ARRAY['Modern/Contemporary','Shaped Wedding Band'] WHERE sku = 'BJ-126';
UPDATE products SET ring_styles = ARRAY['Modern/Contemporary','Shaped Wedding Band'] WHERE sku = 'BJ-127';
UPDATE products SET ring_styles = ARRAY['Vintage','Shaped Wedding Band'] WHERE sku = 'BJ-128';
UPDATE products SET ring_styles = ARRAY['Modern/Contemporary','Shaped Wedding Band'] WHERE sku = 'BJ-129';
UPDATE products SET ring_styles = ARRAY['Modern/Contemporary','Shaped Wedding Band'] WHERE sku = 'BJ-130';
UPDATE products SET ring_styles = ARRAY['Modern/Contemporary','Shaped Wedding Band'] WHERE sku = 'BJ-131';
UPDATE products SET ring_styles = ARRAY['Modern/Contemporary','Shaped Wedding Band'] WHERE sku = 'BJ-132';
UPDATE products SET ring_styles = ARRAY['Modern/Contemporary','Shaped Wedding Band'] WHERE sku = 'BJ-133';
UPDATE products SET ring_styles = ARRAY['Modern/Contemporary','Shaped Wedding Band'] WHERE sku = 'BJ-134';
UPDATE products SET ring_styles = ARRAY['Vintage','Shaped Wedding Band'] WHERE sku = 'BJ-135';
UPDATE products SET ring_styles = ARRAY['Vintage','Shoulder Set','Halo'] WHERE sku = 'BJ-136';
UPDATE products SET ring_styles = ARRAY['Vintage','Shoulder Set','Halo'] WHERE sku = 'BJ-137';
UPDATE products SET ring_styles = ARRAY['Vintage','Shoulder Set','Halo'] WHERE sku = 'BJ-139';
UPDATE products SET ring_styles = ARRAY['Vintage','Shoulder Set','Halo'] WHERE sku = 'BJ-140';
UPDATE products SET ring_styles = ARRAY['Vintage','Shoulder Set'] WHERE sku = 'BJ-141';
UPDATE products SET ring_styles = ARRAY['Modern/Contemporary','Halo'] WHERE sku = 'BJ-142';
UPDATE products SET ring_styles = ARRAY['Vintage','Halo'] WHERE sku = 'BJ-143';
UPDATE products SET ring_styles = ARRAY['Vintage','Halo','Shoulder Set'] WHERE sku = 'BJ-144';
UPDATE products SET ring_styles = ARRAY['Vintage','Halo','Shoulder Set'] WHERE sku = 'BJ-145';
UPDATE products SET ring_styles = ARRAY['Vintage','Halo','Shoulder Set'] WHERE sku = 'BJ-146';
UPDATE products SET ring_styles = ARRAY['Vintage','Halo','Shoulder Set'] WHERE sku = 'BJ-147';
UPDATE products SET ring_styles = ARRAY['Vintage','Halo'] WHERE sku = 'BJ-148';
UPDATE products SET ring_styles = ARRAY['Vintage','Halo'] WHERE sku = 'BJ-149';
UPDATE products SET ring_styles = ARRAY['Vintage','Halo','Shoulder Set'] WHERE sku = 'BJ-150';
UPDATE products SET ring_styles = ARRAY['Vintage','Shoulder Set'] WHERE sku = 'BJ-151';
UPDATE products SET ring_styles = ARRAY['Vintage','Shoulder Set'] WHERE sku = 'BJ-152';
UPDATE products SET ring_styles = ARRAY[]::TEXT[] WHERE sku = 'BJ-050';
UPDATE products SET ring_styles = ARRAY[]::TEXT[] WHERE sku = 'BJ-051';
UPDATE products SET ring_styles = ARRAY[]::TEXT[] WHERE sku = 'BJ-052';
UPDATE products SET ring_styles = ARRAY[]::TEXT[] WHERE sku = 'BJ-053';
UPDATE products SET ring_styles = ARRAY[]::TEXT[] WHERE sku = 'BJ-058';
UPDATE products SET ring_styles = ARRAY[]::TEXT[] WHERE sku = 'BJ-059';
UPDATE products SET ring_styles = ARRAY[]::TEXT[] WHERE sku = 'BJ-060';